Removing test_rpc.cpp
/usr/bin/ld: Tests/unit/core/CMakeFiles/WPEFramework_test_core.dir/test_rpc.cpp.o: undefined reference to symbol '_ZN12WPEFramework7Logging15BaseLoggingTypeINS0_5ErrorEE8_controlE'
/usr/bin/ld: /home/runner/work/Thunder/Thunder/Debug/build/Thunder/Source/messaging/libWPEFrameworkMessaging.so.1: error adding symbols: DSO missing from command line