Test_rpc still seems to be broken
/usr/bin/ld: Tests/unit/core/CMakeFiles/WPEFramework_test_core.dir/test_rpc.cpp.o: undefined reference to symbol '_ZN12WPEFramework9Messaging11MessageUnit8InstanceEv'
/usr/bin/ld: /home/runner/work/Thunder/Thunder/MinSizeRel/build/Thunder/Source/messaging/libWPEFrameworkMessaging.so.1: error adding symbols: DSO missing from command line