No need to redefine __APPLE_USE_RFC_3542 macro as it is already defined in the cmake
And having it redefined here caused warnings treated as errors:

/Users/runner/work/Thunder/Thunder/Thunder/Source/core/Portability.h:440:9: error: '__APPLE_USE_RFC_3542' macro redefined [-Werror,-Wmacro-redefined]
#define __APPLE_USE_RFC_3542
        ^
<command line>:7:9: note: previous definition is here
#define __APPLE_USE_RFC_3542 1
        ^