Removing test_hash.cpp
/usr/bin/ld: Tests/unit/core/CMakeFiles/WPEFramework_test_core.dir/test_hash.cpp.o: undefined reference to symbol '_ZN12WPEFramework6Crypto6SHA2245InputEPKht'
/usr/bin/ld: /home/runner/work/Thunder/Thunder/MinSizeRel/build/Thunder/Source/cryptalgo/libWPEFrameworkCryptalgo.so.1: error adding symbols: DSO missing from command line