[Actions] Fix errors due to an update of GitHub hosted runners (#1774)
* Try to install jsonref with pipx in the external env

* Use the development template to test the patch

* Cannot use pipx on this runner, try to create a virtual env instead

* Make sure to activate the virtual enviroment before building

* Move the activation after the paths update

* Try with sudo

* Make sure to only activate the venv when needed

* Remove the advanced download as it might casue issues

* Make the installation easier

* Try pipx in a different wa

* Try without sudo

* Try venv again

* Use pip instead of pipx

* Remove installing of jsonref for now to test

* Remove venv activation for now

* For now install everything apart from jsonref to isolate the issue

* Remove deactivation of venv

* Add venv again but don't active it yet in the generators

* See if activating the venv fixes this single issue with c++ compiler

* Activate the venv for the Thunder build as well

* Add the libstdc++-multilib to the 32-bit build

It looks like the 32-bit C++ compiler is missing...

* Install libstdc++-11-dev:i386 instead

* Add libc6-dev:i386

* Look for Alternative Package Names

* Make sure to install GCC 13 multilib instead of 11

* Add using CHANNEL::Handle

* Handle in SocketPort is private so cannot use using

* Disable the overloaded virtuals warning

* Move the warning push from cpp to the header

* Add a PUSH_WARNING(DISABLE_WARNING_OVERLOADED_VIRTUALS) to Handle()

* Fix the free() call on a pointer with the nonzero offset

FAILED: Source/com/CMakeFiles/ThunderCOM.dir/Communicator.cpp.o 
/usr/bin/c++ -DBLUEZ_HAS_NO_INCLUSIVE_LANGUAGE -DCOM_EXPORTS -DNO_INCLUSIVE_LANGUAGE -DPROCESSCONTAINERS_ENABLED=1 -DThunderCOM_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_BLUETOOTH_SUPPORT__ -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -I/home/runner/work/Thunder/Thunder/Release/build/Thunder/Source/com -I/home/runner/work/Thunder/Thunder/Thunder/Source/com -I/home/runner/work/Thunder/Thunder/Release/build/Thunder/Source/core -I/home/runner/work/Thunder/Thunder/Release/build/Thunder/Source/core/core -I/home/runner/work/Thunder/Thunder/Release/build/Thunder/Source/core/generated/core -I/home/runner/work/Thunder/Thunder/Thunder/Source/core/.. -I/home/runner/work/Thunder/Thunder/Thunder/Source/messaging -I/home/runner/work/Thunder/Thunder/Thunder/Source/messaging/.. -I/home/runner/work/Thunder/Thunder/Thunder/Source/extensions/warningreporting -I/home/runner/work/Thunder/Thunder/Thunder/Source/extensions/warningreporting/.. -I/home/runner/work/Thunder/Thunder/Thunder/Source/extensions/processcontainers -I/home/runner/work/Thunder/Thunder/Thunder/Source/extensions/processcontainers/.. -Wall -Wextra -Wpedantic -Werror -m64 -O3 -DNDEBUG -std=gnu++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-psabi -MD -MT Source/com/CMakeFiles/ThunderCOM.dir/Communicator.cpp.o -MF Source/com/CMakeFiles/ThunderCOM.dir/Communicator.cpp.o.d -o Source/com/CMakeFiles/ThunderCOM.dir/Communicator.cpp.o -c /home/runner/work/Thunder/Thunder/Thunder/Source/com/Communicator.cpp
In file included from /home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/Singleton.h:30,
                 from /home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/ResourceMonitor.h:24,
                 from /home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/DoorBell.h:23,
                 from /home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/core.h:35,
                 from /home/runner/work/Thunder/Thunder/Thunder/Source/com/Module.h:26,
                 from /home/runner/work/Thunder/Thunder/Thunder/Source/com/Communicator.h:24,
                 from /home/runner/work/Thunder/Thunder/Thunder/Source/com/Communicator.cpp:20:
In static member function ‘static void Thunder::Core::ProxyObject<CONTEXT>::operator delete(void*) [with CONTEXT = Thunder::Core::IPCMessageType<1, Thunder::RPC::Data::Init, Thunder::RPC::Data::Setup>]’,
    inlined from ‘Thunder::Core::ProxyObject<CONTEXT>::~ProxyObject() [with CONTEXT = Thunder::Core::IPCMessageType<1, Thunder::RPC::Data::Init, Thunder::RPC::Data::Setup>]’ at /home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/Proxy.h:119:13,
    inlined from ‘uint32_t Thunder::Core::ProxyObject<CONTEXT>::Release() const [with CONTEXT = Thunder::Core::IPCMessageType<1, Thunder::RPC::Data::Init, Thunder::RPC::Data::Setup>]’ at /home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/Proxy.h:138:21,
    inlined from ‘Thunder::Core::ProxyType<CONTEXT>::~ProxyType() [with CONTEXT = Thunder::Core::IPCMessageType<1, Thunder::RPC::Data::Init, Thunder::RPC::Data::Setup>]’ at /home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/Proxy.h:439:39,
    inlined from ‘virtual void Thunder::RPC::CommunicatorClient::StateChange()’ at /home/runner/work/Thunder/Thunder/Thunder/Source/com/Communicator.cpp:524:66:
/home/runner/work/Thunder/Thunder/Thunder/Source/core/../core/Proxy.h:97:23: error: ‘void free(void*)’ called on pointer ‘<unknown>’ with nonzero offset 1056 [-Werror=free-nonheap-object]
   97 |                 ::free(stAllocateBlock);
      |                 ~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

* Don't forget to free the originalPointer

* Add using Core::WorkerPool::Snapshot to the WorkerPoolImpl

* Remove the changes as they don't fix the issue

* Try one more solution

* Try one more idea..

* Add DISABLE_WARNING_FREE_NONHEAP_OBJECT

* Suppress the warning for now and investigate futher later on

* Developnment finished, use the master template again

* Install jsonref in venv for the tests as well

* Sadly we have to do the merging twice